version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: testPassWord1
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: ghcr.io/momenmarwan/watch-tower-demo:latest
    container_name: my-app
    environment:
      DATABASE_URL: postgresql://postgres:testPassWord1@postgres:5432/test
    depends_on:
      - postgres
    networks:
      - app-network
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:Z
    command: --interval 30 --cleanup
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
